name: build_docker

on:
  push:
    branches: [main]
  release:
    types: [created] # This will only run on new releases

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Print out all environment variables
      - run: |
          env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-web:${{ env.RELEASE_DATE }}
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-web:latest
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            RELEASE_VERSION=${{ github.ref_name }}
